plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'ch.dispo.modules.legacypreferences'
version = '0.1.0'

android {
  namespace "ch.dispo.modules.legacypreferences"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  testImplementation 'junit:junit:4.13.2'
}
